config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  as :user do
    delete 'logout', to: 'users/sessions#destroy'
  end
  resources :members
  get 'home/index'
  get 'home/about'
  get 'home/upcoming'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:index, :about, :upcoming, :show]
    include Devise::Controllers::Helpers
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :branch, :urn, :role)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]
  

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to team_url(@team), notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_url(@team), notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name, :urn, :branch, :status)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  
  def new
    super
  end


  def create
    super
  end


  def destroy
    puts "Destroying user session"
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Live Wire', root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Members", members_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Upcoming Events", home_upcoming_path, class:"nav-link" %>
        </li>
        


        
        
      <% if user_signed_in? %>

        
        <li class="nav-item">
          <%= link_to "Add Member", new_member_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

      <% else %>


        <li class="nav-item">
         <%= link_to "Admin", new_user_session_path, class:"nav-link" %>
        </li>


        
      <% end %>


      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>
</br>
<p>LiveWire Club under the Dpt. Of Applied Sciences  initiated in 2022 turned out to be a great success as it's main agenda was to highlight and showcase the talent of every deserving candidate by providing them with a platform. We have conducted several outreach events which included an Open Mic and fundraising for street dogs. We believe that team effort turns out to be quite inspiring when executed with proper strategy. Speak with no Fear is the viewpoint we want to express</p>
</br>
NOTE: This website is under development. If you want to contribute, contact the live wire core team
</br>

app/views/home/index.html.erb
<h1>Welcome to the official website of your favourite LIVE WIRE CLUB, GNDEC.</h1>

</br>
<div style="text-align: center;">
<img src="<%= asset_path('Layer.png') %>" alt="Live Wire" width="200" height="200">
</div>
</br>

app/views/home/upcoming.html.erb
<h1>Our upcoming Event is MEME-O-MAD
</h1>
The event is scheduled on 27th April.
</br>
</br>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Livewire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
    </br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    </br>
    <%= yield %>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </br>
  <div class="field form-group">
   
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>
          </br>
  <div class="field form-group">
    
    <%= form.text_field :branch, class:"form-control", placeholder:"Branch" %>
  </div>
  </br>
  <div class="field form-group">
    
    <%= form.number_field :urn, class:"form-control", placeholder:"URN" %>
  </div>
  </br>
  <div class="field form-group">
    
    <%= form.text_field :role, class:"form-control", placeholder:"Role" %>
  </div>
  
  <div class="field form-group">
  </br>
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>

  <p>
    <strong>Branch:</strong>
    <%= member.branch %>
  </p>

  <p>
    <strong>Urn:</strong>
    <%= member.urn %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= member.role %>
  </p>
</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>
</br>
<div>
  <%= link_to "Show ", @member, class:"btn btn-dark" %> 
  <%= link_to "Go Back", members_path, class:"btn btn-dark" %>
</div>

app/views/members/index.html.erb
<h1>Members</h1>
</br>

<table class="table table table-striped table table-hover table table-bordered" >
  <thead" >
    <tr class="table-dark">
      <th>Name</th>
      <th>Branch</th>
      <th>URN</th>
      <th>Role</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody id="members">
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.branch %></td>
        <td><%= member.urn %></td>
        <td><%= member.role %></td>
        <td align="center"><%= link_to 'Options', member_path(member) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New member', new_member_path, class:"btn btn-dark" %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "GoBack", members_path, class:"btn btn-dark" %>
</div>

app/views/members/show.html.erb
<div class="card form-control" style="width: 40rem;" >
<div class="card-header">
<p>Member Details</p>
</div>
  <div align="center" class="card-body">
    <h1 align="center" class="card-title"><%= @member.name %></h1>
    <h2><%= @member.role %></h2>
    <p class="card-text">
    </br>
    <%= @member.branch %> | 
    <%= @member.urn %></br>
    </br>
    </p>

    <%= link_to "Edit", edit_member_path(@member), class:"btn btn-dark" %> 
  <%= link_to "Go  Back ", members_path, class:"btn btn-dark" %>
  </br>
  </br>
  <%= button_to "Destroy Member", @member, method: :delete, class:"btn btn-dark" %>
  </div>
</div>